image: docker

services:
  - docker:dind

stages:
  - test
  - development
  - production

test:
  stage: test
  tags:
    - almaat
    - rakeb
    - website

  only:
    - develop
    - production
  script:
    - echo "run tests in this section"

deploy:
  stage: production
  tags:
    - almaat
    - rakeb
    - website

  only:
    - master
  script:
    # - sudo apt-get install -y python3-pip
    # - sudo pip3 install  setuptools
    # - sudo pip3 install docker-compose
    - sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - sudo docker image prune -f
    - sudo docker-compose build --no-cache
    - sudo docker-compose  stop
    - sudo docker-compose  kill
    - sudo docker-compose  rm
    - sudo docker-compose up -d
  when: manual
