version: "3"

services:
  nuxt:
    build: .
    container_name: rakeb-website
    restart: always
    ports:
      - "3000"
    command: "npm run start"

  nginx:
    image: nginx:1.13
    container_name: rakeb-website-nginx
    ports:
      - "3014:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
